apiVersion: v1
kind: Pod
metadata:
  name: alex-apptrust
  labels:
    app: alex-apptrust
spec:
  imagePullSecrets:
    - name: jfrog-docker-config
  containers:
    - name: app
      image: demo.jfrogchina.com/docker-local/alex-apptrust:latest
      imagePullPolicy: Always
      env:
        - name: APP_STAGE
          value: DEV
        - name: APP_VERSION
          value: "1.0.0"
      ports:
        - name: http
          containerPort: 3000
      readinessProbe:
        httpGet:
          path: /healthz
          port: 3000
        initialDelaySeconds: 5
        periodSeconds: 10
      livenessProbe:
        httpGet:
          path: /healthz
          port: 3000
        initialDelaySeconds: 10
        periodSeconds: 20
