apiVersion: v1
kind: Pod
metadata:
  name: runtime-sample-maven
  labels:
    app: runtime-sample-maven
spec:
  imagePullSecrets:
    - name: jfrog-docker-config
  containers:
    - name: app
      image: demo.jfrogchina.com/docker-local/runtime-sample-maven:1.0.3-amd64
      imagePullPolicy: Always
      ports:
        - name: http
          containerPort: 8080
      readinessProbe:
        tcpSocket:
          port: 8080
        initialDelaySeconds: 20
        periodSeconds: 10
      livenessProbe:
        tcpSocket:
          port: 8080
        initialDelaySeconds: 30
        periodSeconds: 20
